### ISSUE TITLE
SB, TB and added skills don't create attributes

### ISSUE THREAD

**Issue by Maetco** [timothystone/roll20-character-sheets#3] opened 2015-03-13 16:31 UTC
This is problematic because now I can't link token abilities to them.

**Comment by timothystone** [comment] 2015-03-13 18:54
Confirmed. The problem is in calculated attributes where the field is `disabled`. It is not sending the data to the backend to store on update.

**Comment by timothystone** [comment] 2015-03-28 00:08
I will fix SB and TB. Please open new issues for "added skills" (not sure what that is actually, but I think you mean that Advance Skills don't create underlying attributes).

**Comment by timothystone** [comment] 2016-03-29 16:04
Fixed in #12. Sorry @Maetco for such a long delay. I use this sheet in my campaign and I've been very lazy. Also fixed an hidden issue with wounds in #11.

**Closed as completed by timothystone** 2016-03-29 16:04 UTC
Labels: bug
